---
title: "03-25"
author: "林茂廷"
date: "3/25/2020"
output: html_document
---

## Atomic vector

```{r}
num1 <- 5
vNum1 <- c(2,5)
vNum2 <- c(2, num1)
# 右邊num1是在call num1, 會得到5，相當於
vNum2 <- c(2,5)
```

Stacking vectors
```{r}
vNum1 <- c(-1,5)
vNum2 <- c(2,3)
vNum3 <- c(vNum1,vNum2)
vNum4 <- c(-1,5,2,3)
vNum5 <- c(c(-1,5),c(2,3))
```

```{r}
vNumComplex <- c(c(1,3,c(-5,23)))
vNumComplexNotComplesAtAll <-
  c(1,3,-5,23)
```

Vector stacking
```{r}
vNum1 <- c(-1,5)
vNum2 <- c(2,3)
vNum4 <- c() # 空向量
```


```{r}
vNum3 <- c(vNum2, vNum1)
vNum4 <- c(vNum4, vNum1) # 向量疊代 （recursive vector concatenate）
```


## Different types

### Numeric

```{r}
num1<-5 # 非整數
num2<-5L # 整數

num1Vector<-c(5,6,7)
num2Vector<-c(5L,6L,7L)
```

```{r}
typeof(num1Vector)
typeof(num2Vector)
```
### Character

```{r}
char1<-c("你好")
char2<-c('你好')
```

他說："今天多了一個確診。"

```{r}
HeSaid <- "他說：\"今天多了一個確診。\""
```

```{r}
HeSaid <- 
  '他說："今天多了一個確診。"'
```

```{r}
char1Vector<-c(
  "你好",
  "How are you?"
  )
```

### Atomic

```{r}
complexVector <- c("小明今年歲數", "15")
```


```{r}
library(httr)
library(dplyr)
GET("https://api.github.com/repos/tpemartin/108-2-56-inclass-practice/commits") %>%
  content() %>%
  View()
```

```{r}
library(googlesheets4)
`出席狀況表單網址` <-  https://docs.google.com/spreadsheets/d/1EAG49qDKPWWi0ebkVr29TLrvVnoBPfkvxYY-J3xLAHY/edit#gid=458686645 # 缺乏定義值
ss <- as_sheets_id(`出席狀況表單網址`)
homework_sheet <- sheets_read(ss,sheet=1)
```

```{r}
library(googlesheets4)
`出席狀況表單網址` <- 'ss' # 缺乏定義值
'ss' <-  ("https://docs.google.com/spreadsheets/d/1EAG49qDKPWWi0ebkVr29TLrvVnoBPfkvxYY-J3xLAHY/edit#gid=458686645")
homework_sheet <- sheets_read(ss,sheet=1)
```

```{r}
library(googlesheets4)
`https://docs.google.com/spreadsheets/d/1EAG49qDKPWWi0ebkVr29TLrvVnoBPfkvxYY-J3xLAHY/edit#gid=458686645` <-
  "https://docs.google.com/spreadsheets/d/1EAG49qDKPWWi0ebkVr29TLrvVnoBPfkvxYY-J3xLAHY/edit#gid=458686645"
`出席狀況表單網址` <- `https://docs.google.com/spreadsheets/d/1EAG49qDKPWWi0ebkVr29TLrvVnoBPfkvxYY-J3xLAHY/edit#gid=458686645` # 缺乏定義值
ss <- as_sheets_id(`出席狀況表單網址`)
homework_sheet <- sheets_read(ss,sheet=1)
```
## logics

```{r}
logi1 <- c(T,TRUE,F,FALSE,FALSE)
```

```{r}
sum(logi1)
```

### Extended atomic vectors

```{r}
# 10位學生的主系
majors10_char <- c('經濟學系','社會學系','社會學系','經濟學系','經濟學系','社會學系','經濟學系','經濟學系','經濟學系','社會學系')

typeof(majors10_char)
class(majors10_char)
```

```{r}
majors10_factor <- factor(majors10_char)
# 或
majors10_factor <- factor(
  c('經濟學系','社會學系','社會學系','經濟學系','經濟學系','社會學系','經濟學系','經濟學系','經濟學系','社會學系')
)

typeof(majors10_factor)
class(majors10_factor)
```


```{r}
levels(majors10_factor)
```

